Gruntfile.js
README.md
tasks-internal/modules/interfaces.d.ts
tasks/modules/html2ts.js
tasks/modules/html2ts.ts
tasks/modules/interfaces.d.ts
tasks/ts.js
tasks/ts.ts
test/htmlOutDir/reference.ts
test/htmlOutDir/src/bar.ts
test/htmlOutDir/src/test.tpl.html
test/htmlOutDirFlat/reference.ts
test/htmlOutDirFlat/src/bar.ts
test/htmlOutDirFlat/src/test.tpl.html

Hi,
I need to be able to have my generated .html.ts file stored in a separate directory from the original template html files. My solution is to provide a htmlOutDir option, where all the generated files are stored.
```javascript
htmlWithHtmlOutDirTest: {
test: true,
src: ['test/htmlOutDir/reference.ts','test/htmlOutDir/src/bar.ts',
'test/htmlOutDir/src/foo.ts',
'test/htmlOutDir/generated/**/*.ts'],
html: ['test/htmlOutDir/**/*.tpl.html'],
reference: 'test/htmlOutDir/reference.ts',
htmlOutDir: 'test/htmlOutDir/generated',
out: 'test/htmlOutDir/out.js'
},
```
One criticism I have of my own solution is that the files are stored flat (all in the same directory) so collisions may occur. I would be happy to hear any alternatives/alterations to my solution

PR: Add option to specify the output directory for generated .html.ts file

---

tasks/modules/amdLoader.js
tasks/modules/amdLoader.ts
tasks/modules/reference.js
tasks/modules/reference.ts
tasks/modules/templateCache.js
tasks/modules/templateCache.ts
tasks/modules/transformers.js
tasks/modules/transformers.ts
tasks/modules/utils.js
tasks/modules/utils.ts
test/htmlOutDir/reference.ts
test/htmlOutDirFlat/reference.ts

I abstracted out the call to grunt.util.linefeed to a single variable in utils.ts to make it easy to maintain later so if grunt were to change the parameter name or if you wanted to make a user option, you would only need to change the code in one place. Besides running all the tests, I also tested it in one of my repos and confirmed I was able to get LF endings when running a grunt-ts task on Windows.

Replace uses of os.EOL with grunt.util.linefeed

---

sample/Gruntfile.js

The sample Gruntfile includes commas which are not needed. The WebStorm IDE issues warnings because of the unneeded comes. That's why I removed them.

Removed unneeded commas.

---

Gruntfile.js
tasks/modules/html2ts.js
tasks/modules/html2ts.ts
test/expected/htmlTemplate/out.js
test/htmlTemplate/src/advanced.$$template.name.tpl.html
test/htmlTemplate/src/foo.ts
test/test.js
test/test.ts

When compiling html files with names containing periods, the compile function creates invalid ts output.
Options used:
```
options: {
htmlModuleTemplate: 'Templates',
htmlVarTemplate: '<%= filename %>_<%= ext %>'
}
```
Example:
``test.view.example.index.html`` -> ``test.view.example.index.html.ts``
Outputs ``test.view.example.index.html.ts``:
```
module mctUntitledAppTemplates_Dev { export var test_view.example.index_html =  '<html><body>Hello world' }
```
Which then causes a compile error:
```
test.view.example.index.html.ts(1,58): error TS1005: ',' expected.
test.view.example.index.html.ts(1,66): error TS1005: ',' expected.
```
This commit includes a basic fix by replacing all occurrences of ``'\.'``. Note that it might be a good idea to replace other special js characters.
I have too …

Add support for file names with multiple periods on them.

---

tasks-internal/modules/compile.js
tasks-internal/modules/compile.ts
tasks/modules/compile.js
tasks/modules/compile.ts

Modified the executeNode(...) helper in the compile module. Changed the value of cmd from the hardcoded string 'node' to the process.execPath value.

Issues #236 - Fix for use of local node binaries.

---

tasks/ts.ts

When using <%= parameter %> in reference config, it is not expanded to actual value. 
Should be fixed with this oneliner.

Ensure reference is using grunt.template.process

---

README.md
docs/html2ts.md
tasks/modules/html2ts.js
tasks/modules/html2ts.ts
tasks/modules/interfaces.d.ts
tasks/ts.js
tasks/ts.ts

In reference to https://github.com/TypeStrong/grunt-ts/issues/208 .
This allows developers to define if the resulting TS will be an internal or an external module.

Adding support for HTML templates as external modules

---

README.md

Submitting a new PR after #261, this time containing just the --emitDecoratorMetadataDocs.

Add documentation for the emitDecoratorMetadata option.

---

tasks/modules/optionsResolver.js
tasks/modules/optionsResolver.ts

with 
```
"compilerOptions": {
"module": "commonjs",
"target": "es5",
"noImplicitAny": true,
"inlineSources": true
},
```
```
$ tsc -p ./
error TS5051: Option 'inlineSources' can only be used when either option '--inlineSourceMap' or option '--sourceMap' is provided.
```

tsc allow use inlineSources with sourceMap option

---

Gruntfile.js
tasks-internal/modules/optionsResolver.js
tasks-internal/modules/optionsResolver.ts
tasks/modules/optionsResolver.js
tasks/modules/optionsResolver.ts
test/expected/htmlExternal/html.external.html.ts

After moving from 4.x to 5.1 I noticed that the html template stopped working. I pulled down the source and tracked down the issue. It looks like htmlOutputTemplate was missing from the delayTemplateExpansion array and grunt would replace the placeholders as it would try and resolve them (so your generated html.ts files would not have the html content). I looked to add a test but it looks like one was added but not being run correctly (it needed the html settings within the options object and the settings and expected template needed some tweaks to get the diff passing. As I was preparing this pull request I noticed someone else had also picked up on this issue as well.

htmlOutputTemplate bug

---

tasks/modules/compile.js
tasks/modules/compile.ts

Sorry for the lack of tests. :cry:

Fast compilation should work if there are type errors and failOnTypeErrors is false

---

Gruntfile.js
tasks/modules/html2ts.js
tasks/modules/html2ts.ts
test/expected/htmlSnakeModuleName/out.js
test/htmlSnakeModuleName/reference.ts
test/htmlSnakeModuleName/src/foo.ts
test/htmlSnakeModuleName/src/snake-module-name.tpl.html
test/test.js
test/test.ts

When compiling html files with names containing dashes, the compile function creates invalid ts output.
I've started using dashes in my file names as suggested by [JohnPapa's style guide](https://github.com/johnpapa/angular-styleguide#style-y121).  This pull request is inspired by https://github.com/TypeStrong/grunt-ts/pull/237
Options used:
```
options: {
htmlModuleTemplate: '<%= filename %>_<%= ext %>_module',    // Template for module name for generated ts from html files [(default) '<%= filename %>']
htmlVarTemplate:    '<%= filename %>_<%= ext %>_variable',  // Template for variable name used in generated ts from html files [(default) '<%= ext %>]
},
```
Example:
`example-page.tpl.html` -> `example-page.tpl.html.ts`
Outputs
```
/* tslint:disable:max-line-length */
module …
```

Add support for file names with multiple dashes on them.

---

CHANGELOG.md
README.md

As far as I can tell the default behavior of --moduleResolution is "classic". The docs should reflect this.

Update README -> moduleResolution description -> default behavior

---

tasks/modules/compile.ts

Per the docs, https://www.typescriptlang.org/docs/handbook/compiler-options.html the module option does support "none"

Support for none an option for module

---

.travis.yml
package.json

Hi!
In the context of https://github.com/TypeStrong/grunt-ts/issues/369 I've created this mini PR with:
- Chokidar updated to latest version (1.6)
- Add node 4,5 and 6 to Travis build
I've run the tests in my local with node 6 and they work and I also tested with the original repo where the issue came up and it also works.
Thanks!
Fran

Adding support for Node 6

---

README.md

Hi,
This PR is to updating readme.md, since 'module' property can be 'amd' or 'system' instead of 'commonjs'.
Thank you for accepting it.
Cheers,
Yan

#361 update readme.md,  'module' property can be 'amd' or 'system' instead of 'commonjs'

---

Gruntfile.js
README.md
package.json
tasks/modules/compile.js
tasks/modules/compile.ts
tasks/modules/defaults.js
tasks/modules/defaults.ts
tasks/modules/interfaces.d.ts
tasks/modules/optionsResolver.js
tasks/modules/optionsResolver.ts
tasks/modules/tsconfig.js
tasks/modules/tsconfig.ts
test/commandLineAssertions.js
test/commandLineAssertions.ts

`noImplicitThis`, `strictNullChecks`, `lib` options are added. This should solve #360.
May you kindly review the code and merge it, thank you.

Support some options from TypeScript 2.0

---

package.json
tasks/modules/interfaces.d.ts
tasks/modules/tsconfig.js
tasks/modules/tsconfig.ts
test/optionsResolverTests.js
test/optionsResolverTests.ts
test/tsconfig_artifact/extends/configs/base.json
test/tsconfig_artifact/extends/tsconfig.json
test/tsconfig_artifact/extends/tsconfig.nostrictnull.json

Add support to grunt-ts for tsconfig.json `extends` feature.  Also supports comments in the tsconfig.json now (by minifying the file before calling JSON.parse()).

Support tsconfig.json extends

---

tasks/ts.ts

Added support for .jsx, .tsx, and .js file extensions in the handleFileEvent function.
Tests remained the same after changes in addition to not introducing any breaking changes.
This PR fixes issue #363.

Altered handleFileEvent to be able to accept extensions other than .ts and .html

---

Gruntfile.js
tasks/ts.js
tasks/ts.ts
test/baseDirOption/baseDirNotSpecified/foo/bar.ts
test/baseDirOption/baseDirSpecified/foo/bar.ts
test/commandLineAssertions.js
test/commandLineAssertions.ts

According to README of grunt-ts, when `--outDir` option is specified, `baseDir` is not specified and the value of `fast` option is "never", `.baseDir.ts` file should not be created. But in that case, `.baseDir.ts` file is created actually. I think this is a bug.
- `.baseDir.ts` file is created when `baseDir` option is specified
- `.baseDir.ts` file is created when fast compile is enabled
- `.baseDir.ts` file is **NOT CREATED** when `baseDir` option is not specified and fast compile is not enabled
- `.baseDir.ts` file is created when `baseDir` option is specified
- `.baseDir.ts` file is created when fast compile is enabled
- `.baseDir.ts` file is **CREATED** when `baseDir` option is not specified and fast compile is not enabled
- Added tests for `baseDir` option : …

Fix: not to create `.baseDir.ts` file in case that `baseDir` is not specified and fast compile is not enabled

---

.npmignore
package.json

Taking a swing at a fixing #287, this PR includes a couple of things:
1. Adds a few extra resources to `.npmignore` so they aren't included in the package
2. Points the `"main"` attribute in `package.json` to the right place

Cleanup npm package (#287)

---

README.md
tasks/modules/compile.ts
tasks/modules/defaults.ts
tasks/modules/interfaces.d.ts
tasks/modules/optionsResolver.ts
test/expected/allowJs/result.js

When fast-compiling project with `.d.ts` files caching them meaning some typings will be missing,
this allows the user to control what get cached or not.

Support regex to prevent custom file from being cached

---

package.json

accept any grunt version 1.x as peer dependency (fix for issue 430)
